repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: demo-api-spotless-check
        name: demo-api-spotless-check
        entry: mvn -B -ntp -f services/demo-api/pom.xml spotless:check
        language: system
        pass_filenames: false
