{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "demo-api.fullname" . }}
  labels:
{{ include "demo-api.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "demo-api.selectorLabels" . | indent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
