replicaCount: 2

image:
  repository: 205474063511.dkr.ecr.us-east-1.amazonaws.com/java-application
  tag: fd7d6d47bfd1acfaf04eb2fe89a638e8146f9381
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

ingress:
  enabled: true
  className: nginx
  host: demo.example.com
  tlsSecret: demo-tls
