replicaCount: 2
team: platform

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/demo-api
  tag: fd7d6d47bfd1acfaf04eb2fe89a638e8146f9381
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

rollout:
  enabled: true
  revisionHistoryLimit: 5
  canary:
    maxSurge: 25%
    maxUnavailable: 0
    analysis:
      startingStep: 2
    steps:
    - setWeight: 20
    - pause:
        duration: 2m
    - setWeight: 50
    - pause:
        duration: 5m
    - setWeight: 100
  analysis:
    prometheusAddress: http://prometheus-operated.monitoring.svc:9090
    interval: 1m
    count: 3
    failureLimit: 1
    minSuccessRate: 0.99

ingress:
  enabled: true
  className: nginx
  host: demo.example.com
  tlsSecret: demo-tls
