apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
spec:
  destination:
    namespace: demo-dev
  source:
    helm:
      parameters:
      - name: image.tag
        value: 0.1.0-dev
