apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
spec:
  destination:
    namespace: demo-dev
  source:
    helm:
      parameters:
      - name: image.tag
        value: fd7d6d47bfd1acfaf04eb2fe89a638e8146f9381



