apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
spec:
  destination:
    namespace: demo-dev
  source:
    helm:
      parameters:
      - name: image.tag
        value: a04fe95656e9cf9e0bfe8261ec04f131756e382c

